config/routes.rb
Hadith::Application.routes.draw do
  devise_for :users

  root :to => 'books#index'

  resources :books do
    resources :chapters, :except => [:index] do
      resources :sections
      resources :hadits, :except => [:index]
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :title
  has_many :chapters, dependent: :destroy
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :title, :chnum, :tgtnum
  has_many :hadits, dependent: :destroy
  has_many :sections, dependent: :destroy
  belongs_to :book
end

app/models/hadit.rb
class Hadit < ActiveRecord::Base
  attr_accessible :matan, :chapter_id, :section_id, :hdnum
  belongs_to :chapter
  belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :chapter_id, :title, :scnum
  belongs_to :chapter
  has_many :hadits
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_book, only: [:show, :edit, :destroy, :update]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def show
    @chapters = @book.chapters.sort_by(&:chnum)
  end

  def edit
  end

  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to books_path
    else
      render action => 'new', flash: { failed: "Failed adding book" }
    end
  end

  def destroy
    if @book.destroy 
      redirect_to books_path, flash: { success: "Book removed" }
    end
  end

  def update
    if @book.update_attributes(params[:book])
      redirect_to books_path, flash: { success: "Book updated." }
    else
      render action: "edit", flash: { failed: "Book failed to update." }
    end
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  before_filter :find_book
  before_filter :find_chapter, only: [:show, :edit, :update, :destroy]

  def new
    @chapter = @book.chapters.build
  end

  def show
  end

  def edit
  end

  def update
    if @chapter.update_attributes(params[:chapter])
      flash[:success] = "Chapter has successfully updated."
      redirect_to @book
    else
      render action: 'edit', flash: { failed: 'Check again' }
    end
  end

  def create
    @chapter = @book.chapters.build(params[:chapter])

    if @chapter.save
      flash[:success] = "Chapter has been created."
      redirect_to book_path(@book)
    else
      flash[:alert] = "Chapter has not been created."
      render action: "new"
    end
  end

  def destroy
    @chapter.destroy

    redirect_to book_path(@book), flash: { success: "Chapter removed from #{@book.title}" }
  end

  private

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_chapter
    @chapter = @book.chapters.find(params[:id])
  end
end

app/controllers/hadits_controller.rb
class HaditsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  before_filter :find_book_and_chapter, only: [:new, :show, :edit, :destroy, :create, :update]

  # GET /hadits/1
  # GET /hadits/1.json
  def show
    @hadit = Hadit.find(params[:id])
  end

  # GET /hadits/new
  # GET /hadits/new.json
  def new
    @hadit = @chapter.hadits.build
  end

  # GET /hadits/1/edit
  def edit
    @hadit = Hadit.find(params[:id])
  end

  # POST /hadits
  # POST /hadits.json
  def create
    @hadit = @chapter.hadits.build(params[:hadit])

    respond_to do |format|
      if @hadit.save
        format.html { redirect_to [@book, @chapter, @hadit], flash: { success: 'Hadit was successfully created.'}}
      else
        flash[:alert] = "Check again"
        format.html { render action: "new" }
      end
    end
  end

  # PUT /hadits/1
  # PUT /hadits/1.json
  def update
    @hadit = Hadit.find(params[:id])

    respond_to do |format|
      if @hadit.update_attributes(params[:hadit])
        flash[:success] = "Hadith was successfully updated."
        format.html { redirect_to book_chapter_path(@book, @chapter) }
      else
        flash[:alert] = "Check again."
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /hadits/1
  # DELETE /hadits/1.json
  def destroy
    @hadit = @chapter.hadits.find(params[:id])
    @hadit.destroy

    respond_to do |format|
      format.html { redirect_to book_chapter_path(@book, @chapter) }
    end
  end

  private

  def find_book_and_chapter
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.find(params[:chapter_id])
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_filter :find_section, :only => [:destroy, :edit, :update]
  before_filter :find_book_and_chapter

  def new
    @section = @chapter.sections.build
  end

  def edit
  end

  def create
    @section = @chapter.sections.build(params[:section])

    if @section.save
      redirect_to book_chapter_path(@book, @chapter), flash: { success: "Section successfully created." }
    else
      render action: "new", flash: { failed: "Section failed to save." }
    end
  end

  def destroy

  end

  def update
    if @section.update_attributes!(params[:section])
      redirect_to [@book, @chapter], flash: { success: "Section successfully updated." }
    else
      render action: "edit", flash: { failed: "Section failed to update." }
    end
  end

  private

  def find_book_and_chapter
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.find(params[:chapter_id])
  end

  def find_section
    @section = Section.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
  def calculate_progress(chapter)
    finished = Hadit.where(chapter_id: chapter.id).count
    target = if chapter.tgtnum.nil? then 100 else chapter.tgtnum end
    return finished.to_f / target.to_f * 100
  end
end

app/helpers/hadits_helper.rb
module HaditsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
    <br/>
    <%= f.label :author, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, class: 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default:t("helpers.links.cancel")), books_path, class: 'btn' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1>Edit Book Title</h1>
</div>
<%= render partial: 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1>Available Books</h1>
</div>

<p class="lead"> List of Available Hadith Books </p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Book Title</th>
      <th>Book Author</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.author %></td>
        <% if user_signed_in? %>
          <td style="text-align: right;">
            <%= link_to raw('<i class="icon-pencil"></i>'),
            edit_book_path(book), alt: "Edit this book" %>
            <%= link_to raw('<i class="icon-remove"></i>'), 
              book_path(book), confirm: 'Are you sure?', method: :delete, alt: "Delete this book" %>
          </td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Book",
            new_book_path(@book),
            class: 'btn btn-primary' if user_signed_in?%>

app/views/books/new.html.erb
<div class="page-header">
  <h1>Create New Book</h1>
</div>

<%= render partial: 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>

<div class="page-header">
  <h1><%= @book.title %></h1>
</div>

<ul class="nav nav-tabs" id="#chapter-tab">
  <li class="active"><a href="#chapter-list" data-toggle="tab">Chapters</a></li>
  <li><a href="#book-details" data-toggle="tab">Details</a></li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade active in" id="chapter-list">
    <p class="lead">List of available chapters</p>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>#</th><th>Chapter Name</th>
          <% if user_signed_in? %>
            <th>Progress</th>
            <th><span class="pull-right">Actions</span></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @chapters.each do |chapter| %>
          <tr>
            <td><span class="badge badge-info"><%= chapter.chnum %></span></td>
            <td><%= link_to chapter.title, book_chapter_path(@book, chapter) %></td>
            <% if user_signed_in? %>
              <td width="150">
                  <div class="progress">
                    <div class="bar bar-success" style="width: <%= calculate_progress(chapter) %>%;">
                  </div>
                </td>
                <td style="text-align: right;">
                  <%= link_to raw('<i class="icon-pencil"></i>'),
                    edit_book_chapter_path(@book, chapter), alt: "Edit this chapter" %>
                  <%= link_to raw('<i class="icon-remove"></i>'), 
                    book_chapter_path(@book, chapter), confirm: 'Are you sure?', method: :delete, alt: "Delete this chapter" %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to "Back",
        books_path,
        class: 'btn' %>
      <%= link_to "New Chapter",
        new_book_chapter_path(@book),
        class: 'btn btn-primary' if user_signed_in?%>
    </div>

    <div class="tab-pane" id="book-details">
      details here
    </div>
  </div>

  <script>
    $(function () {
      $('#chapter-tab a:last').tab('show');
      $('#book-details a:last').tab('show');
    })
  </script>

app/views/chapters/_form.html.erb
<%= form_for [@book, @chapter], html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :chapter_number, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :chnum, class: 'text_field' %>
    </div><br/>
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div><br/>
    <%= f.label :number_of_hadits, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :tgtnum, class: 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default:t("helpers.links.cancel")), book_path(@book), class: 'btn' %>
<% end %>

app/views/chapters/edit.html.erb
<%- model_class = Chapter -%>
<div class="page-header">
  <h1>Edit Chapter Title</h1>
</div>
<%= render partial: 'form' %>

app/views/chapters/new.html.erb
<div class="page-header">
  <h1>Create New Chapter</h1>
</div>
<p class="lead">New Chapter in <%=link_to @book.title, book_path(@book) %> : </p>
<%= render partial: 'form' %>

app/views/chapters/show.html.erb
<div class="page-header" style="text-align: center;">
  <h1>
    <%= @chapter.title %>
    <br/>
    <span style="font-size: 30%">
      <%= link_to "Back", book_path(@book), class: "btn btn-small" %>
      <%= link_to "Add Section", new_book_chapter_section_path(@book, @chapter), 
        class: "btn btn-primary btn-small" if user_signed_in? %>
    </span>
  </h1>
</div>

<% @chapter.sections.sort_by(&:scnum).each do |section| %>
  <div class="lead" style="text-align: center;">
    <%= section.title %>
    <br/>
    <% if user_signed_in? %>
      <span style="font-size: 50%">
        <%= link_to "Edit Section", edit_book_chapter_section_path(@book, @chapter, section) %> |
        <%= link_to "Add Hadith", new_book_chapter_hadit_path(@book, @chapter, section) %>
      </span>
    <% end %>
  </div>
  <table class="table table-striped table-hover">
    <% section.hadits.sort_by(&:hdnum).each do |hadit| %>
      <tr>
        <td>
          <span class="badge badge-info">
            <%= hadit.hdnum %>
          </span>
        </td>
        <td>
          <div>
            <%= hadit.matan %>
            <%= link_to :details, book_chapter_hadit_path(@book, @chapter, hadit), html: {class: "btn btn-info"} %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/hadits/_form.html.erb
<%= form_for [@book, @chapter, @hadit], html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :section, class: 'control-label' %>
    <div class="controls">
      <%= f.select :section_id, @chapter.sections.collect{ |s| [ s.title, s.id ] }, include_black: 'None' %>
    </div><br/>
    <%= f.label :hadits_number, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :hdnum, class: 'text_field' %>
    </div><br/>
    <%= f.label :matan, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :matan, class: 'span6', cols: '10', rows: '10' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                book_chapter_path(@book, @chapter), class: 'btn' %>
  </div>
<% end %>

app/views/hadits/edit.html.erb
<%- model_class = Hadit -%>
<div class="page-header">
  <h1>Edit Hadith</h1>
</div>
<%= render partial: 'form' %>

app/views/hadits/index.html.erb
<%- model_class = Hadit -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:matan) %></th>
      <th><%= model_class.human_attribute_name(:book) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @hadits.each do |hadit| %>
      <tr>
        <td><%= link_to hadit.id, hadit_path(hadit) %></td>
        <td><%= hadit.matan %></td>
        <td><%= hadit.book %></td>
        <td><%=l hadit.created_at %></td>
        <td>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                      edit_hadit_path(hadit), class: 'btn btn-mini' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      hadit_path(hadit),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                      class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_hadit_path,
            class: 'btn btn-primary' %>

app/views/hadits/new.html.erb
<%- model_class = Hadit -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human %></h1>
</div>
<%= render partial: 'form' %>

app/views/hadits/show.html.erb
<%- model_class = Hadit -%>

<div class="page-header"></div>
<p class="lead">
  <%= link_to @chapter.title, book_chapter_path(@book, @chapter) %>, 
  <%= link_to @book.title, book_path(@book) %> 
</p>
<p class="hadit-matan"><%= @hadit.matan %></p>

<% if user_signed_in? %>
  <div class="form-actions">
    <%= link_to t('.back', default: t("helpers.links.back")),
                book_chapter_path(@book, @chapter), class: 'btn'  %>
    <%= link_to t('.edit', default: t("helpers.links.edit")),
                edit_book_chapter_hadit_path(@book, @chapter, @hadit), class: 'btn' %>
    <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                book_chapter_hadit_path(@book, @chapter, @hadit),
                method: 'delete',
                data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                class: 'btn btn-danger' %>
  </div>
<% else %>
  <div class="form-actions">
		<%= link_to :tweet, "http://#{request.host}:#{request.fullpath}", class: "twitter-share-button" %>
  </div>
<% end %>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hadith</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">{Hadith}</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Browse books", books_path %></li>
            </ul>
            <% unless user_signed_in? %>
              <ul class="nav pull-right">
                <li><%= link_to "Sign in", new_user_session_path %></li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div id="wrap">
      <div class="container">
        <% if user_signed_in? %>
          <div class="row">
            <p class="text-warning pull-right"> 
            Signed in as : <%= current_user.email %> | 
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </p>
        </div>
      <% end %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <div id="push"></div>
  </div>

  <div id="footer">
    <div class="container">
      <p class="muted credit">
      Copylefted to 
      <a href="#">TaegukWarriors</a>
      and 
      <a href="#">Ninjas</a>.
      </p>
    </div>
  </div>
</body>
</html>

app/views/sections/_form.html.erb
<%= form_for [@book, @chapter, @section], html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :section_number, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :scnum, class: 'text_field' %>
    </div><br/>
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default:t("helpers.links.cancel")), book_chapter_path(@book, @chapter), class: 'btn' %>
<% end %>

app/views/sections/edit.html.erb
<div class="page-header">
  <h2>Edit Section</h2>
</div>

<%= render partial: "form" %>

app/views/sections/new.html.erb
<div class="page-header">
  <h1>New Section</h1>
</div>

<%= render partial: "form" %>